language: generic

services:
   - docker 

deploy:
   provider: elasticbeanstalk
   region: us-east-1
   app: "mydocker"
   env: "myfirstapp-env"

   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY

   bucket_name: "my-first-bucket"

   bucket_path: "docker"

   on:
     branch: main